name: Synchronize Insight.com Labels
on:
  pull_request:
    types:
      - synchronize
      - closed

jobs:
  Synchronize-labels:
    name: Synchronize
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout iw-prototype
        uses: actions/checkout@v2
        with:
          repository: Insight-IT-Web/iw-prototype
          path: iw-prototype
          ref: lokalise
          clean: true
          token: ${{ secrets.WEB_TO_LOKALISE }}
      - name: Synchronize iw-prototype labels
        run: |
            for item in packages/*/;
            do
              module=$(basename $item)
              echo "$module"
                if [ -d  $module/src/assets/labels ]; then
                  if [ -d iw-prototype/packages/$module/src/assets/labels ]; then
                    rm -Rf iw-prototype/packages/$module/src/assets/labels
                  fi
                  mkdir -p iw-prototype/packages/$module/src/assets/labels
                  cp -R  $module/src/assets/labels iw-prototype/packages/$module/src/assets/
                fi
            done
            cd iw-prototype
            git remote set-url origin https://${{ secrets.WEB_TO_LOKALISE }}@github.com/Insight-IT-Web/iw-prototype.git
            git config --global user.email "pjetly@insight.com"
            git config --global user.name "Pooja jetly"
            git status
            git add .
            git status
            git commit -m "PRT-1234 synchronizing iw-prototype labels"
            git push
        shell: bash
